### ISSUE TITLE
adding auto reload to celery

### ISSUE THREAD

**Issue by avico78** [testdrivenio/fastapi-celery#1]
Thanks for a great tutorial , really helpful

Questions please:

1.is the reason we are locating worker code inside the fastapi is to allow celery "see" fastapi parameters?
If yes , how can celery work use fastapi parameters/objects?
I.e - in fastapi usually we keep all DB connection and if i want to move some heavy computing from 
fastapi --> celery worker , is there an easy way to pass parameters/objects from fastapi to worker?
i'd like to avoid holding 2 set of parameters and configuration ,

2.Im trying to add more functionalities to celery ,
It would be really helpful if u could demonstrate the approach for adding new task and the meaning of delay
and should use it (got lost with celery documentations)
3.It would be really helpful if u could explain how to add celery auto reload - so it would be easier see result immediately and not required to reboot the docker ,

thanks again for your work !

**Comment by mjhea0** [comment]
1. Depends on your project structure. If you have a *config.py* file in "project" you can just import that file into *worker.py* to get access. 
2. We're going to be adding a FastAPI + Celery course here soon, which will address those questions. Until then, I recommend going through the https://testdriven.io/courses/flask-celery/ course.
3. The https://testdriven.io/courses/flask-celery/ course also addresses the auto-reload issue.

Feel free to reach out over email if you have more questions. michael at testdriven dot io

**Comment by avico78** [comment]
> 1. Depends on your project structure. If you have a _config.py_ file in "project" you can just import that file into _worker.py_ to get access.
> 2. We're going to be adding a FastAPI + Celery course here soon, which will address those questions. Until then, I recommend going through the https://testdriven.io/courses/flask-celery/ course.
> 3. The https://testdriven.io/courses/flask-celery/ course also addresses the auto-reload issue.
> 
> Feel free to reach out over email if you have more questions. michael at testdriven dot io

Thanks a lot @mjhea0
