### ISSUE TITLE
AssertionError: jinja2 must be installed to use Jinja2Templates

### ISSUE THREAD

**Issue by juliangeissler** [testdrivenio/fastapi-celery#2]
Hi, 
i get this error inside the docker container:
`AssertionError: jinja2 must be installed to use Jinja2Templates`
when running the docker-compose up command.

What I did:
```
git clone https://github.com/testdrivenio/fastapi-celery --branch v1 --single-branch
cd fastapi-celery
git checkout v1 -b master
docker-compose up -d --build
```

I googled this error but didnt find a solution yet. The container runs locally. The files are on it. The requirements are installed

Do you have an idea?

Edit:
I get the same error when i clone the full repo

```
git clone https://github.com/testdrivenio/fastapi-celery
cd fastapi-celery
docker-compose up -d --build
```

**Comment by marrocksd** [comment]
> 

I tried the latest ver of Jinja and it works. Seem like they hardcoded the version for fastapi, not starlette and uvicorn. So the latest version of starlette got installed and wasn't compatible with the old version of jinja

**Comment by juliangeissler** [comment]
@marrocksd Indeed, that did the trick. I added a pull request to upgrade the Jinja2 version

Thank you!
